config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  resources :questions do
  	resources :answers
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers
	validates :qtext, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:twitter]

  	def self.from_omniauth(auth)
	  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		    user.email = auth.info.email
		    user.password = Devise.friendly_token[0,20]
		    # If you are using confirmable and the provider(s) you use validate emails, 
		    # uncomment the line below to skip the confirmation emails.
		    # user.skip_confirmation!
	  	end
	end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		@question = Question.find(params[:question_id])
		@answer = @question.answers.create(answer_params)
		redirect_to question_path(@question)
	end

	def destroy
		@question = Question.find(params[:question_id])
		@answer = @question.answers.find(params[:id])
		@answer.destroy
		redirect_to post_path(@question)
	end


	private def answer_params
		params.require(:answer).permit(:body)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	
	def new
  		@question = Question.new()
	end

	def index
		@questions = Question.all
	end

	def show
		@question = Question.find(params[:id])
	end

	def create
		#render plain: params[:post].inspect
		@question = Question.new(question_params)
		if(@question.save)
			redirect_to @question
		else
			render "new"
		end
	end


	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		if(@question.update(question_params))
			redirect_to @question
		else
			render 'edit'
		end
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy

		redirect_to questions_path
	end


	private def question_params
		params.require(:question).permit(:qtext, :description)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def destroy
		session[:user_id] = nil
		session[:omniauth] = nil
		redirect_to root_url, notice: "signed out successfully"

	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      auth = request.env["omniauth.auth"].except("extra")
      session[:omniauth] = auth
      user = User.from_omniauth(auth)
      session[:user_id] = user.id
      redirect_to root_path, notice: "signed in successfully"
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answers.html.erb
<h3>Answers</h3>

<% @question.answers.each do |answer| %>
	<div class="well">
		<p><strong>Username</strong>: <%= answer.body %>

	<%= link_to "[X]", [answer.question, answer],
					method: :delete,
					data: {confirm: 'Are you sure?'} %>

		</p>
	</div>
<% end %>

app/views/answers/_form.html.erb
<h3>Answer this question</h3>

<%= form_for([@question, @question.answers.build]) do |f| %>

	<p>
		<%= f.label :body, "Answer" %><br/>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-default', :value => 'Submit'}) %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <style type="text/css">
    body {
      padding-top: 10rem;
      text-align: center;
      }
    .starter-template {
      padding: 3rem 1.5rem;
      text-align: center;
    }
    </style>
    
    <title>Myapp</title>
    
    <%= csrf_meta_tags %>

  
    <%= stylesheet_link_tag 'bootstrap.css' %>
    <%= stylesheet_link_tag 'bootstrap-theme.css' %>
    <%= stylesheet_link_tag 'bootstrap.min.css' %>
    <%= stylesheet_link_tag 'bootstrap-theme.min.css' %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=<%= root_url %>>Q&A app</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <% @auth = session[:omniauth] if session[:omniauth] %>
          <ul class="nav navbar-nav">
            <% if current_user %>
                <li>
                  <%= link_to "Ask a question", new_question_path %>
                </li>
            <% elsif @auth %>
              <li> <%= link_to "Ask a question", new_question_path %></li>
            <% else %>
              <li>
                <%= link_to "Login", new_user_session_path %>
              </li>
              <li>
                <%= link_to "Twitter login", user_twitter_omniauth_authorize_path %>
              </li>
              <li>
                <%= link_to "Register", new_user_registration_path %>
              </li>
            <% end %>


          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete %>
              </li>
            <% elsif @auth %>
              <li>
                <%= image_tag(@auth['info']['image'], width: '50', height: '50', class: 'image-circle')%></li>
                <li><%= link_to "Logout", {:controller => "sessions", :action => "destroy"} %>
              </li>
            <% end  %>

          </ul>
        </div>
      </div>
    </nav>


    <!-- Page Content -->

    <div class="container">

      <div class="row">
        <div class="col-lg-12 text-center">
          <% flash.each do |a, b| %>
            <div class="alert alert-success"> <%= b %> </div>
          <% end %>          
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= form_for :question, url: question_path(@question), method: :patch do |f| %>

	<% if @question.errors.any? %>
		<% @question.errors.full_messages.each do |msg| %>
			<div class = "alert alert-danger"><%= msg %></div>
		<% end %>	
	<% end %>	


	<p>
		<%= f.label :qtext, 'What is your question?' %><br/>
		<%= f.text_field(:qtext, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :description, 'Detailed description' %><br/>
		<%= f.text_area(:description, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary', :value => 'Submit'}) %>
	</p>

<% end %>

app/views/questions/index.html.erb
<h1>Questions Home Page</h1>

<% @questions.each do |question| %>
	<div class="well">
		<h3><%= question.qtext %></h3>
		<p><%= question.description %></p>
		<%= link_to "View Question", question_path(question), :class => 'btn btn-default' %>
	</div>
<% end %>

app/views/questions/new.html.erb
<h1>Ask question</h1>

<%= form_for :question, url: questions_path do |f| %>

	<% if @question.errors.any? %>
		<% @question.errors.full_messages.each do |msg| %>
			<div class = "alert alert-danger"><%= msg %></div>
		<% end %>	
	<% end %>	


	<p>
		<%= f.label :qtext, 'What is your question?' %><br/>
		<%= f.text_field(:qtext, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :description, 'Detailed description' %><br/>
		<%= f.text_area(:description, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary', :value => 'Submit'}) %>
	</p>
<% end %>

app/views/questions/show.html.erb
<h2><%= @question.qtext %></h2>

<p><%= @question.description %></p>
<hr>

<%= link_to "Edit", edit_question_path(@question), :class => 'btn btn-default' %>

<%= link_to "Delete", question_path(@question),
					method: :delete,
					data: {confirm: 'Are you sure?'},
						
					:class => 'btn btn-danger' %>


<hr>
<%= render 'answers/answers' %>
<hr>
<%= render 'answers/form' %>
<hr>